<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <!-- NuGet Package Metadata -->
  <PropertyGroup>
    <PackageId>Himmelt.ModbusLib</PackageId>
    <Version>1.0.3</Version>
    <Authors>Himmelt</Authors>
    <Company>Himmelt</Company>
    <Description>一个功能完整、高性能的Modbus客户端库，基于.NET 10平台，支持多种Modbus协议变体。</Description>
    <Copyright>Copyright © 2024-2026 Himmelt</Copyright>
    <PackageProjectUrl>https://github.com/Himmelt/ModbusLib</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Himmelt/ModbusLib</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Tags>modbus, modbus-rtu, modbus-tcp, modbus-udp, .net, dotnet, client, protocol</Tags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Title>ModbusLib</Title>
    <PackageTags>modbus;modbus-rtu;modbus-tcp;modbus-udp;.net;dotnet;client;protocol</PackageTags>
    <PackageReleaseNotes>fix(SerialTransport): 修复字符间隔超时检查逻辑</PackageReleaseNotes>
    <PackageIcon>nuget_logo.png</PackageIcon>
  </PropertyGroup>

  <!-- 包含README.md文件到NuGet包 -->
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nuget_logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>